### ISSUE TITLE
Cannot run psiphon test

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#448]
So here's what I do in a clean debian jessie vm:
# install psiphon
$ scripts/psiphon_install.sh

```
bash: hg: command not found
```
--> installed mercurial
```
scripts/psiphon_install.sh: 70: scripts/psiphon_install.sh: virtualenv: not found
```
--> installed python-virtualenv

# running psiphon test:
```
$ ooniprobe -ng third_party/psiphon -u http://google.com
```
```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
Not reporting using a collector
You should add annotations for the country, city and ASN
Fetching required net test inputs...
Looking up collector and test helpers
[!] Error performing request: http://google.com
Report ID: 4hyL8C9GStLpPrri3d1nkknxmmxd9wZVBVvR7NMeLYpfQ9UBZe3DG0dGBWl2lRRN
Main loop terminated.
```

## Complete report output:

```
###########################################
# OONI Probe Report for psiphon_test (0.0.1)
# Sat Dec 19 17:47:04 2015
###########################################
---
annotations: null
input_hashes: []
options: [-u, google.com]
probe_asn: AS0
probe_cc: ZZ
probe_city: null                                                                                                                                                                      
probe_ip: 127.0.0.1
report_id: 4hyL8C9GStLpPrri3d1nkknxmmxd9wZVBVvR7NMeLYpfQ9UBZe3DG0dGBWl2lRRN
software_name: ooniprobe
software_version: 1.3.2
start_time: 1450547224.0
test_helpers: {}
test_name: psiphon_test
test_version: 0.0.1
...
---
/usr/bin/python /tmp/tmpwIauF9: {exit_reason: process_done, stderr: '', stdout: ''}
agent: agent
input: null
psiphon_installed: true
requests:
- failure: connection_refused_error
  request:
    body: null
    headers: []
    method: GET
    tor: {is_tor: false}
    url: http://google.com
socksproxy: 127.0.0.1:1080
test_runtime: 28.053759813308716
test_start_time: 1450547224.0
```
## Running it in debug mode:
```
# ooniprobe -ng third_party/psiphon -u http://google.com
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
Not reporting using a collector
[D] No test deck detected
[D] UsageOptions
You should add annotations for the country, city and ASN
Fetching required net test inputs...
Looking up collector and test helpers
[D] Creating /root/ooni-probe/report-psiphon_test-2015-12-19T175031Z.yamloo
[D] Writing report with YAML reporter
[D] Starting this task <generator object generateMeasurements at 0x7f1ac08fecd0>
[D] Running <class 'ooni.nettests.third_party.psiphon.PsiphonTest'> test_psiphon
[D] PiphonTest._setUp: setting socksproxy
[D] Finished test setup
[D] PsiphonTest.setUp
[D] psiphon path: /root/psiphon-circumvention-system/pyclient
[D] command: /usr/bin/python/tmp/tmpSmUPPY
[D] PsiphonTest.test_psiphon
[D] Adding {'test_start_time': 1450547431.0, 'input': None, 'psiphon_installed': True, 'agent': 'agent', 'socksproxy': '127.0.0.1:1080'} to report
[D] Checking all tasks for completion 0 == 1
[D] STDOUT: Traceback (most recent call last):\r\n  File "/tmp/tmpSmUPPY", line 2, in <module>\r\n    from psi_client import connect\r\n  File "/root/psiphon-circumvention-system/p#
[D] STDOUT: ImportError: No module named pexpect\r\n
[D] Exited [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process e#
[D] Ended [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process en#
[D] Finished ['/usr/bin/python', '/tmp/tmpSmUPPY']: {'exit_reason': 'process_done', 'stderr': '', 'stdout': 'Traceback (most recent call last):\\r\\n  File "/tmp/tmpSmUPPY", line 2#
[D] PsiphonTest:cleanup
[D] Task <ooni.tasks.Measurement object at 0x7f1abfffadd0> has failed 2 times
Traceback (most recent call last):
  File "/tmp/src/ooniprobe/ooni/tasks.py", line 76, in _timedOut
    self._running.cancel()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 478, in cancel
    self.errback(failure.Failure(CancelledError()))
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/tmp/src/ooniprobe/ooni/nettests/third_party/psiphon.py", line 129, in cleanup
    self.processDirector.transport.signalProcess('INT')
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 362, in signalProcess
    raise ProcessExitedAlready()
twisted.internet.error.ProcessExitedAlready:
[D] Rescheduling...
[D] PsiphonTest.test_psiphon
[D] Adding {'psiphon_installed': True, 'socksproxy': '127.0.0.1:1080', 'test_start_time': 1450547431.0, 'agent': 'agent', 'input': None, '/usr/bin/python /tmp/tmpSmUPPY': {'exit_re#
[D] Using SOCKS proxy 127.0.0.1:1080 for request
[D] Performing request http://google.com GET {}
[!] Error performing request: http://google.com
[D] Adding {'url': 'http://google.com', 'headers': {}, 'body': None, 'method': 'GET', 'tor': {'is_tor': False}} to report
[D] PsiphonTest:cleanup
[D] Exited [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process e#
[D] Ended [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process en#
[D] Finished ['/usr/bin/python', '/tmp/tmpSmUPPY']: {'exit_reason': 'process_done', 'stderr': '', 'stdout': ''}
[D] Successfully completed measurement: <ooni.tasks.Measurement object at 0x7f1abfffadd0>
[D] Starting this task <ooni.tasks.ReportEntry object at 0x7f1ac0cd6c10>
[D] Writing report with YAML reporter                                                                                                                                                
[D] Successfully performed report <ooni.tasks.ReportEntry object at 0x7f1ac0cd6c10>
[D] None
[D] Checking all tasks for completion 1 == 1
Report ID: OaZtWyjQYPyAaHs7cPttfQnVim7oNvd3YLM6Un1xynuony3UXfIdFOsozxG60kWS
[D] Successfully performed measurement <ooni.tasks.Measurement object at 0x7f1abfffadd0>
[D] {'exit_reason': 'process_done', 'stderr': '', 'stdout': ''}
Main loop terminated.
```
## Report output
```
###########################################
# OONI Probe Report for psiphon_test (0.0.1)
# Sat Dec 19 17:50:31 2015
###########################################
---
annotations: null
input_hashes: []
options: [-u, google.com]
probe_asn: AS0
probe_cc: ZZ
probe_city: null
probe_ip: 127.0.0.1
report_id: OaZtWyjQYPyAaHs7cPttfQnVim7oNvd3YLM6Un1xynuony3UXfIdFOsozxG60kWS
software_name: ooniprobe
software_version: 1.3.2
start_time: 1450547431.0
test_helpers: {}
test_name: psiphon_test
test_version: 0.0.1
...
---
/usr/bin/python /tmp/tmpSmUPPY: {exit_reason: process_done, stderr: '', stdout: ''}
agent: agent
input: null
psiphon_installed: true
requests:
- failure: connection_refused_error
  request:
    body: null
    headers: []
    method: GET
    tor: {is_tor: false}
    url: http://google.com
socksproxy: 127.0.0.1:1080
test_runtime: 28.072322130203247
test_start_time: 1450547431.0
```
