### ISSUE TITLE
The localOptions are overwritten when the same test is run with different options in a deck

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#493]
The current mechanism for setting the localOptions of tests was written when there was no notion of test decks.

As a result of this the object lifecycle was such that it was OK to have the `localOptions` attribute of `NetTestCase` be static. Since the introduction of test decks it's possible to have multiple tests of the same type run with different options, though since `localOptions` is a static attribute it will be overwritten with the last parsed option in the deck by subsequent calls to `NetTestLoader.checkOptions`.

Here is a minimal way of reproducing this bug:

```
#!/bin/bash
cat <<EOF > broken.deck
- options:
    collector: null
    help: 0
    logfile: null
    no-default-reporter: 0
    parallelism: null
    pcapfile: null
    reportfile: null
    resume: 0
    subargs: [-f, 'list1.txt']
    test_file: blocking/tcp_connect
- options:
    collector: null
    help: 0
    logfile: null
    no-default-reporter: 0
    parallelism: null
    pcapfile: null
    reportfile: null
    resume: 0
    subargs: [-f, 'list2.txt']
    test_file: blocking/tcp_connect
EOF
echo "8.8.8.8:53" > list1.txt
echo "8.8.4.4:53" > list2.txt
```
Then run it with `ooniprobe -n -i broken.deck`.

By inspecting the tcp_connect reports you can then confirm that both of them include only the `8.8.4.4`  IP address and the first one doesn't contain the `8.8.8.8`.

The current recommended workaround is to not use conflicting options in decks when using the same test name.

Fixing this bug should be of very high priority as I believe it also impacts the ability to properly run the default decks generated with `oonideckgen`.
