### ISSUE TITLE
http_requests returns exit_ip: null and exit_name: null

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#509]
ooniprobe version: 1.4.2
test: blocking/http_requests
`ooniprobe -f /etc/ooniprobe/ooniprobe.conf blocking/http_requests --url http://cnn.com`
```
- failure: null
  request:
    body: null
    headers: {User-Agent: 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.7)
        Gecko/20091221 Firefox/3.5.7'}
    method: GET
    tor: {exit_ip: null, exit_name: null, is_tor: true}
    url: http://cnn.com
  response:
    body: "<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body bgcolor=\"\
      white\">\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx</center>\r\
      \n</body>\r\n</html>\r\n"
    code: 301
    headers: {Content-Type: text/html, Date: 'Thu, 19 May 2016 21:18:08 GMT', Location: 'http://www.cnn.com/',
      Server: nginx, Set-Cookie: 'CG=RO:--:--; path=/', X-UA-Profile: desktop}
socksproxy: null
test_runtime: 1.227489948272705
```
```
[D] Adding {'url': 'http://cnn.com', 'headers': {'User-Agent': ['Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6']}, 'body': None, 'method': 'GET', 'tor': {'is_tor': False, 'exit_name': None, 'exit_ip': None}} to report
[D] Successfully completed measurement: <ooni.tasks.Measurement object at 0x743b7250>
[D] Successfully performed measurement <ooni.tasks.Measurement object at 0x743b7250>
[D] <twisted.web._newclient.Response object at 0x746b1050>
[D] Got response <twisted.web._newclient.Response object at 0x7439de10>
[D] Processing response body
[D] Adding {'url': 'http://cnn.com', 'headers': {'User-Agent': ['Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.7) Gecko/20091221 Firefox/3.5.7']}, 'body': None, 'method': 'GET', 'tor': {'is_tor': True, 'exit_name': None, 'exit_ip': None}} to report
[D] Successfully completed measurement: <ooni.tasks.Measurement object at 0x746b1e10>
The two body lengths appear to match
censorship is probably not happening
Headers appear to match
[D] Starting this task <ooni.tasks.ReportEntry object at 0x746b1bf0>
[D] Writing report with YAML reporter
[D] Successfully performed report <ooni.tasks.ReportEntry object at 0x746b1bf0>
[D] None
[D] Starting this task <ooni.tasks.ReportEntry object at 0x746b1f50>
[D] Writing report with OONIB reporter
[D] Updating report with id 20160520T224227Z_AS1916_nPGz3MtmxQCqzmlZQbmLKJHZ5MBoEfdRrlnOis8JdDuCA3jCk8 (http://ihiderha53f36lsd.onion/report/20160520T224227Z_AS1916_nPGz3MtmxQCqzmlZQbmLKJHZ5MBoEfdRrlnOis8JdDuCA3jCk8)
[D] Sending {"content": {"test_keys": {"control_failure": null, "socksproxy": null, "headers_diff": [], "agent": "agent", "experiment_failure": null, "control_cloudflare": false, "body_proportion": 1.0, "factor": 0.8, "body_length_match": true, "requests": [{"failure": null, "request": {"body": null, "headers": {"User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6"}, "tor": {"is_tor": false, "exit_name": null, "exit_ip": null}, "url": "http://cnn.com", "method": "GET"}, "response": {"body": "<html>\\r\\n<head><title>301 Moved Permanently</title></head>\\r\\n<body bgcolor=\\"white\\">\\r\\n<center><h1>301 Moved Permanently</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n", "headers": {"Set-Cookie": "CG=BR:--:--; path=/", "X-UA-Profile": "desktop", "Server": "nginx", "Location": "http://www.cnn.com/", "Date": "Fri, 20 May 2016 22:43:13 GMT", "Content-Type": "text/html"}, "code": 301}}, {"failure": null, "request": {"body": null, "headers": {"User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.7) Gecko/20091221 Firefox/3.5.7"}, "tor": {"is_tor": true, "exit_name": null, "exit_ip": null}, "url": "http://cnn.com", "method": "GET"}, "response": {"body": "<html>\\r\\n<head><title>301 Moved Permanently</title></head>\\r\\n<body bgcolor=\\"white\\">\\r\\n<center><h1>301 Moved Permanently</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n", "headers": {"Set-Cookie": "CG=FR:--:--; path=/", "X-UA-Profile": "desktop", "Server": "nginx", "Location": "http://www.cnn.com/", "Date": "Fri, 20 May 2016 22:43:14 GMT", "Content-Type": "text/html"}, "code": 301}}], "headers_match": true}, "software_version": "1.4.2", "measurement_start_time": "2016-05-20 22:43:13", "test_start_time": "2016-05-20 22:43:08", "probe_asn": "AS1916", "test_name": "http_requests", "software_name": "ooniprobe", "annotations": null, "data_format_version": "0.2.0", "test_runtime": 1.1328721046447754, "options": ["--url", "cnn.com"], "test_version": "0.2.5", "input_hashes": [], "input": "http://cnn.com", "probe_ip": "127.0.0.1", "report_id": "20160520T224227Z_AS1916_nPGz3MtmxQCqzmlZQbmLKJHZ5MBoEfdRrlnOis8JdDuCA3jCk8", "probe_city": null, "id": "f5557378-baf6-485b-9201-630598834084", "test_helpers": {}, "probe_cc": "BR"}, "format": "json"}
[D] Successfully performed measurement <ooni.tasks.Measurement object at 0x746b1e10>
[D] <twisted.web._newclient.Response object at 0x7439de10>
[D] Checking all tasks for completion 1 == 2
[D] Checking all tasks for completion 2 == 2
[...]
[D] None
Main loop terminated.
```
