### ISSUE TITLE
ooniprobe 1.5.1-1 (debian) daily cronjob fails

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#542]
Debian stretch
ooniprobe 1.5.1-1

---

It seems that the ooniprobe cronjob fails:

`/var/log/ooni/ooniprobe.log` output:

```
[-] Looking up your IP address via torproject
[-] Found your IP via a GeoIP service
[-] Fetching required net test inputs...
[-] Looking up collector and test helpers
[-] [!] Lookup failed. Retrying.
[-] [!] Lookup failed. Retrying.
[-] [!] Lookup failed. Retrying.
[-] [!] Failed. Giving up.
[-] Traceback (most recent call last):
[-]   File "/usr/lib/python2.7/dist-packages/ooni/backend_client.py", line 173, in lookupTestCollector
[-]     query={'net-tests': net_tests})
[-]   File "/usr/lib/python2.7/dist-packages/ometa/protocol.py", line 53, in dataReceived
[-]     self._parser.receive(data)
[-]   File "/usr/lib/python2.7/dist-packages/ometa/tube.py", line 41, in receive
[-]     status = self._interp.receive(data)
[-]   File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 48, in receive
[-]     for x in self.next:
[-]   File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 166, in apply
[-]     for x in self._apply(f, ruleName, argvals):
[-]   File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 104, in _apply
[-]     for x in rule():
[-]   File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 245, in parse_Or
[-]     for x in self._eval(subexpr):
[-]   File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 230, in parse_And
[-]     for x in self._eval(subexpr):
[-]   File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 423, in parse_Action
[-]     val = eval(expr.data, self.globals, self._localsStack[-1])
[-]   File "<string>", line 1, in <module>
[-]   File "/usr/lib/python2.7/dist-packages/txsocksx/client.py", line 153, in serverResponse
[-]     raise e.socks5ErrorMap.get(status)()
[-] HostUnreachable
[-] [!] Could not start the director
[-] [!] Could not find a valid collector.
[-] Try with a different bouncer, specify a collector with -c or disable reporting to a collector with -n.
[-] Main loop terminated.
```

Contents of: `/etc/cron.daily/ooniprobe`

```
#!/bin/sh

set -e

sh -n /etc/default/ooniprobe 2>/dev/null || exit 0

. /etc/default/ooniprobe
test "$OONIPROBE_RUN_DAILY_TEST" = 'true' || exit 0

test -f /var/lib/ooni/decks/debian-default/user.deck || exit 0

fix_permissions() {
        local user group mode path

        read user group mode path
        chown $user:$group $path
        chmod $mode $path
}

if ! [ -d /var/log/ooni ]; then
        mkdir /var/log/ooni
        { dpkg-statoverride --list /var/log/ooni ||
          echo Debian-ooni adm 750 /var/log/ooni
        } | fix_permissions
fi

# Remove incomplete reports from former runs
su Debian-ooni -c 'oonireport -f /etc/ooniprobe.conf status' |
sed -n -e '/^Incomplete reports/,$s/^\* //p' | while read path; do
        rm -f "$path"
done

# Try to upload unsent reports
su Debian-ooni -c 'oonireport -f /etc/ooniprobe.conf upload' >> /var/log/ooni/oonireport.log

# Run daily test
flock --nonblock /run/oonprobe.daily.lock su Debian-ooni -c "cd /var/lib/ooni/reports && ooniprobe -f /etc/ooniprobe.conf -i /var/lib/ooni/decks/debian-default/user.deck" > /dev/null
```

Contents of: `/var/lib/ooni/decks/debian-default/user.deck`

```
- options:
    annotations: null
    bouncer: null
    collector: null
    no-collector: 0
    no-geoip: 0
    no-yamloo: 0
    reportfile: null
    subargs: &id001 []
    test_file: manipulation/http_invalid_request_line
    verbose: 0
- options:
    annotations: null
    bouncer: null
    collector: null
    no-collector: 0
    no-geoip: 0
    no-yamloo: 0
    reportfile: null
    subargs: *id001
    test_file: manipulation/http_header_field_manipulation
    verbose: 0
- options:
    annotations: null
    bouncer: null
    collector: null
    no-collector: 0
    no-geoip: 0
    no-yamloo: 0
    reportfile: null
    subargs: [-f, /var/lib/ooni/decks/debian-default/citizenlab-urls-global.txt]
    test_file: blocking/web_connectivity
    verbose: 0
```
