### ISSUE TITLE
[EPIC] New test deck format

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#571]
The current deck definition is starting to show it's limitations. It's limitations are becoming even more apparent as I am implementing the web UI and I think the time may have come to make some drastic changes to it.

I will write here what are my thoughts on this and what are the limitations of the current approach and possible ways forward.

### Current limitations

* Since the top level of a deck is current an array structure, this means that we are very limited in how we can expand it (it's not possible to add extra keys that have special meaning to it)

* The paths to input files inside of the deck descriptions need to be absolute paths. This is particularly problematic if you need to move the deck file around as that requires that you also adjust the paths in the deck itself.

* The decks are not particularly user friendly and they are only specific to ooniprobe.

* There is no notion of variables inside of decks. This means that, for example, if I want to reference a particular constant file path inside of a deck I can't do it. 

I think we can design a new deck format that overcomes the above issues and is also more expandable to support also a wider array of testing tools such as measurement-kit, neubot, etc.

I would like decks to be in some way similar to how ansible playbooks work and mirroring their type of syntax.

I would say that for the purpose of the web UI implementation we have minimal deck that supports the current features:

* Having some metadata about the deck embedded inside of it

* Allowing the possibility of referencing file paths as relative

* Minimal variable support with a sort of templating language

* Expandable to support more "task" types that are not just ooniprobe specific 

In this new deck format the default deck would look something like this:

```
---
title: Default ooniprobe deck
description: This is the default deck
tasks:
- name: Runs the HTTP Header Field Manipulation test
  ooni:
    test_name: http_header_field_manipulation

- name: Runs the HTTP Invalid Request Line test
  ooni:
    test_name: http_invalid_request_line

- name: Runs the Web Connectivity Test
  ooni:
    test_name: web_connectivity
    file: $input_citizen_lab_global_urls

- name: Runs the Web Connectivity Test
  ooni:
    test_name: web_connectivity
    file: $input_citizen_lab_${probe_cc}_urls
```

Regarding the usage of `$input_citizen_lab_global_txt`, to avoid adding any extra unnecessary dependencies the minimal variable substitution based templating system of python could be used (https://www.python.org/dev/peps/pep-0292/).

If there are some strong reasons to use something more complex such as `jinja2` I am open to discuss that.

@bassosimone
